title: Sinan Grehan
author: Sinan Grehan
url: "https://sinangrehan.github.io"
description: >
  Graduate student at UChicago (MSCAPP) interested in civic tech and applying
  computational skills to meaningful policy problems.
permalink: /:slug
favicon: "./favicon.ico"
twitter:
  username: ""
  card: summary_large_image
remote_theme: abhinavs/moonwalk
theme_config:
  appearance: "dark"
  appearance_toggle: true
  back_home_text: "home.."
  date_format: "%B %-d, %Y"
  show_description: true
  show_navbar: true
  show_footer: true
  show_copyright: true
  show_projects: true
  show_misc_list: false
  show_blog: false
  show_old_projects: false
  home:
    title_projects: "Projects"

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate

social:
  name: Sinan Grehan
  links:
    - https://github.com/sinangrehan
    - https://www.linkedin.com/in/sinan-grehan-58b48b280
